"""
Tests for app/processing/parser.py

Parser responsibilities:
- Read all sheets dynamically
- Detect header row per sheet
- Normalize column names (lowercase, strip)
- Map each sheet's columns to canonical names BEFORE concatenation
- Build DataFrame per sheet with _source_sheet column
- Concatenate valid sheets into one DataFrame

Output columns are CANONICAL (First, Last, etc.) not source aliases.
This is the key change from the original design — mapping now happens
per-sheet inside the parser to correctly handle multi-sheet workbooks
with different column aliases.
"""
import logging
import pytest
import pandas as pd
from app.tests.fixtures import build_workbook
from app.processing.parser import parse_workbook


# --- Shared config used across all tests ---
MAPPING_CONFIG = {
    "header_scan_rows": 20,
    "fields": {
        "First": ["first_name", "fname", "first"],
        "Last": ["lastname", "last_name", "lname", "last"],
        "Address1": ["address1", "address", "addr"],
        "City": ["city"],
        "State": ["st", "state", "state_code"],
        "Zip": ["zip", "zip_code", "zipcode"],
        "DonationDate": ["giftdate", "gift_date", "donationdate", "donation_date", "date"],
        "DonationAmount": ["amount", "donationamount", "donation_amount", "gift_amount"],
    },
}


# ---------------------------------------------------------------------------
# Unit tests
# ---------------------------------------------------------------------------

def test_single_sheet_header_row_1():
    """Single sheet with header in row 1 is parsed and mapped correctly."""
    wb = build_workbook([{
        "name": "Alpha Fund",
        "rows": [
            ["First", "Last", "Amount", "GiftDate"],
            ["John", "Doe", "100.00", "2024-01-01"],
            ["Jane", "Smith", "200.00", "2024-01-02"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert isinstance(result, pd.DataFrame)
    assert len(result) == 2
    assert "_source_sheet" in result.columns
    assert result["_source_sheet"].iloc[0] == "Alpha Fund"
    # Columns are canonical after per-sheet mapping
    assert "First" in result.columns
    assert "Last" in result.columns
    assert result.iloc[0]["First"] == "John"
    assert result.iloc[1]["First"] == "Jane"


def test_header_offset_row_3():
    """Header detected correctly when metadata rows precede it."""
    wb = build_workbook([{
        "name": "Alpha Fund",
        "rows": [
            ["Prepared for internal review", None, None, None],
            ["Client: Alpha Fund", None, None, None],
            ["First", "Last", "Amount", "GiftDate"],
            ["John", "Doe", "100.00", "2024-01-01"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 1
    assert "First" in result.columns
    assert result["_source_sheet"].iloc[0] == "Alpha Fund"
    assert result.iloc[0]["First"] == "John"


def test_header_offset_row_5():
    """Header detected correctly when offset is deeper (row 5)."""
    wb = build_workbook([{
        "name": "Liberty PAC",
        "rows": [
            ["Report generated by system", None, None],
            ["Date: 2024-01-01", None, None],
            [None, None, None],
            ["Internal use only", None, None],
            ["first_name", "last_name", "gift_amount"],
            ["Alice", "Johnson", "500.00"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 1
    assert "First" in result.columns
    assert result["_source_sheet"].iloc[0] == "Liberty PAC"
    assert result.iloc[0]["First"] == "Alice"


def test_multi_sheet_different_aliases():
    """
    Multi-sheet workbook with DIFFERENT column aliases per sheet.
    Per-sheet mapping ensures both sheets produce canonical column names
    before concatenation — no NaN leakage.
    """
    wb = build_workbook([
        {
            "name": "Alpha Fund",
            "rows": [
                ["First", "Last", "Amount"],
                ["John", "Doe", "100.00"],
            ],
        },
        {
            "name": "Liberty PAC",
            "rows": [
                ["fname", "lname", "gift_amount"],
                ["Jane", "Smith", "200.00"],
            ],
        },
    ])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 2
    alpha_rows = result[result["_source_sheet"] == "Alpha Fund"]
    liberty_rows = result[result["_source_sheet"] == "Liberty PAC"]
    assert len(alpha_rows) == 1
    assert len(liberty_rows) == 1

    # Both use canonical names — no NaN from alias mismatch
    assert alpha_rows.iloc[0]["First"] == "John"
    assert liberty_rows.iloc[0]["First"] == "Jane"

    # No NaN in First or Last columns
    assert result["First"].notna().all()
    assert result["Last"].notna().all()


def test_multi_sheet_different_header_positions():
    """Multi-sheet workbook where each sheet has header at a different row."""
    wb = build_workbook([
        {
            "name": "Sheet A",
            "rows": [
                ["First", "Last", "Amount"],
                ["John", "Doe", "100.00"],
            ],
        },
        {
            "name": "Sheet B",
            "rows": [
                ["Metadata row", None, None],
                ["More metadata", None, None],
                ["fname", "lname", "gift_amount"],
                ["Jane", "Smith", "200.00"],
            ],
        },
    ])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 2
    assert set(result["_source_sheet"].unique()) == {"Sheet A", "Sheet B"}
    # Both sheets produce canonical First column
    assert result["First"].notna().all()


def test_column_names_normalized_and_mapped():
    """Column names are lowercased, stripped, then mapped to canonical names."""
    wb = build_workbook([{
        "name": "Alpha Fund",
        "rows": [
            ["  First  ", "  Last  ", "  Amount  "],
            ["John", "Doe", "100.00"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    # Canonical names present
    assert "First" in result.columns
    assert "Last" in result.columns
    assert "DonationAmount" in result.columns
    # Source aliases must not appear
    assert "  First  " not in result.columns
    assert "first" not in result.columns


def test_source_sheet_column_present_and_correct():
    """_source_sheet column is present and reflects the originating sheet name."""
    wb = build_workbook([{
        "name": "Heritage Trust",
        "rows": [
            ["First", "Last", "zip"],
            ["John", "Doe", "37201"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert "_source_sheet" in result.columns
    assert result["_source_sheet"].iloc[0] == "Heritage Trust"


def test_metadata_row_does_not_trigger_header_detection():
    """Metadata rows must not be mistaken for headers or data."""
    wb = build_workbook([{
        "name": "Alpha Fund",
        "rows": [
            ["Prepared for internal review", None, None, None],
            ["Client: Alpha Fund", None, None, None],
            ["First", "Last", "Amount", "GiftDate"],
            ["John", "Doe", "100.00", "2024-01-01"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    # Exactly 1 data row — metadata rows not treated as data
    assert len(result) == 1
    assert result.iloc[0]["First"] == "John"


# ---------------------------------------------------------------------------
# Edge case tests
# ---------------------------------------------------------------------------

def test_empty_sheet_skipped():
    """Sheet with header but no data rows is skipped without error."""
    wb = build_workbook([
        {
            "name": "Empty Sheet",
            "rows": [
                ["First", "Last", "Amount"],
            ],
        },
        {
            "name": "Good Sheet",
            "rows": [
                ["First", "Last", "Amount"],
                ["John", "Doe", "100.00"],
            ],
        },
    ])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 1
    assert result["_source_sheet"].iloc[0] == "Good Sheet"


def test_sheet_with_no_detectable_header_excluded(caplog):
    """Sheet with no recognizable header is excluded and a warning is logged."""
    wb = build_workbook([
        {
            "name": "Bad Sheet",
            "rows": [
                ["random", "gibberish", "columns"],
                ["a", "b", "c"],
            ],
        },
        {
            "name": "Good Sheet",
            "rows": [
                ["First", "Last", "Amount"],
                ["John", "Doe", "100.00"],
            ],
        },
    ])

    with caplog.at_level(logging.WARNING, logger="app.processing.parser"):
        result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 1
    assert result["_source_sheet"].iloc[0] == "Good Sheet"
    assert "Bad Sheet" in caplog.text


def test_partial_match_below_threshold_excluded():
    """Sheet with only 1 alias match (below threshold of 2) is excluded."""
    wb = build_workbook([{
        "name": "Weak Sheet",
        "rows": [
            ["first", "random_col_1", "random_col_2"],
            ["John", "x", "y"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert result.empty


def test_partial_match_at_threshold_accepted():
    """Sheet with exactly 2 alias matches (at threshold) is accepted."""
    wb = build_workbook([{
        "name": "Threshold Sheet",
        "rows": [
            ["first", "last", "random_col"],
            ["John", "Doe", "x"],
        ],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert len(result) == 1
    assert result.iloc[0]["First"] == "John"


def test_completely_empty_workbook():
    """Workbook with no valid sheets returns empty DataFrame without error."""
    wb = build_workbook([{
        "name": "Empty",
        "rows": [],
    }])

    result = parse_workbook(wb, MAPPING_CONFIG)

    assert isinstance(result, pd.DataFrame)
    assert result.empty


# ---------------------------------------------------------------------------
# Integration test
# ---------------------------------------------------------------------------

def test_multi_sheet_mixed_templates_integration():
    """
    Integration: multi-sheet workbook with mixed templates, metadata rows,
    different header positions, and different aliases produces a single
    correct DataFrame with canonical column names and no NaN leakage.
    """
    wb = build_workbook([
        {
            "name": "Alpha Fund",
            "rows": [
                ["Prepared for internal review", None, None],
                ["Client: Alpha Fund", None, None],
                ["First", "Last", "Amount", "GiftDate", "ST", "Zip"],
                ["John", "Doe", "100.00", "2024-01-01", "TN", "37201"],
                ["Jane", "Smith", "200.00", "2024-01-02", "CA", "90210"],
            ],
        },
        {
            "name": "Liberty PAC",
            "rows": [
                ["fname", "lname", "gift_amount", "state", "zip_code"],
                ["Alice", "Johnson", "500.00", "TX", "75001"],
            ],
        },
        {
            "name": "Instructions",
            "rows": [
                ["This sheet contains instructions", None],
                ["Do not delete", None],
            ],
        },
    ])

    result = parse_workbook(wb, MAPPING_CONFIG)

    # Instructions sheet excluded
    assert set(result["_source_sheet"].unique()) == {"Alpha Fund", "Liberty PAC"}
    assert len(result) == 3

    # All rows have _source_sheet
    assert result["_source_sheet"].notna().all()

    # All columns are canonical
    for col in result.columns:
        if col != "_source_sheet":
            assert col[0].isupper() or col == "_source_sheet", f"Non-canonical column: {col}"

    # No NaN in key fields from alias mismatch
    assert result["First"].notna().all()
    assert result["Last"].notna().all()

    # Data values correct
    alpha_rows = result[result["_source_sheet"] == "Alpha Fund"]
    liberty_rows = result[result["_source_sheet"] == "Liberty PAC"]
    assert len(alpha_rows) == 2
    assert len(liberty_rows) == 1
    assert alpha_rows.iloc[0]["First"] == "John"
    assert liberty_rows.iloc[0]["First"] == "Alice"